name: Build, Deploy to Render

on:
  workflow_run:
    workflows: [CodeQL]
    types:
      - completed
jobs:
  build:
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build Docker image
          run: |
            docker build -t ${{ vars.SERVICE }}:${{ github.sha }} ./

        - name: Save Docker image to tar file
          run: |
            docker save ${{ vars.SERVICE }}:${{ github.sha }} -o ${{ vars.SERVICE }}_${{ github.sha }}.tar

        - name: Upload image artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{ vars.SERVICE }}_${{ github.sha }}
            path: ${{ vars.SERVICE }}_${{ github.sha }}.tar
            retention-days: 1
  deploy-render:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Deploy to Render
          uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}