name: Scale Down Cloud Run Service
on:
  schedule:
    # 5:00 PM PST = 01:00 UTC (next day)
    - cron: '0 1 * * *'

jobs:
  scale-down:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      # - name: Scale Down Cloud Run Service
      #   run: |
      #     gcloud run services update ${{ vars.SERVICE }} \
      #       --region=${{ vars.REGION }} \
      #       --min-instances=0
      - name: 'Scale Down Load Balancer'
        run: |
            gcloud compute backend-services update ${{ vars.BACKEND_NAME }} \
              --region=${{ vars.REGION }} \
              --capacity-scaler=0.0