name: Node.js Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: node --no-warnings ./node_modules/jest/bin/jest.js --config=jest.config.cjs ./tests/index.test.js
      env:
        NODE_ENV: test
        CI: true
      continue-on-error: true
    - name: Status
      run: echo "Tests completed with continue-on-error"
    - name: Upload coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage/
        retention-days: 1